# Generated by Django 5.0.1 on 2024-02-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='singledb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=30, null=True)),
                ('Profile', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
