# Generated by Django 5.0.1 on 2024-02-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_prodb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prodb',
        ),
    ]
