# Generated by Django 5.0.1 on 2024-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_singledb_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='singledb',
            name='City',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='singledb',
            name='State',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
