# Generated by Django 5.0.1 on 2024-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_singledb_city_singledb_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='singledb',
            name='City',
        ),
        migrations.RemoveField(
            model_name='singledb',
            name='State',
        ),
    ]
