# Generated by Django 5.0.1 on 2024-02-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_state_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statedb',
        ),
    ]
