# Generated by Django 5.0.1 on 2024-02-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
