# Generated by Django 5.0.1 on 2024-02-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_bookingdb_paid_bookingdb_razor_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdb',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='bookingdb',
            name='razor_payment_id',
        ),
    ]
