# Generated by Django 5.0.1 on 2024-02-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_bookingdb_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindb',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logindb',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
